### ISSUE TITLE
Enrollment JWT Signer resolution with multiple hostnames/ips fails

### ISSUE THREAD

**Issue by andrewpmartinez** [openziti/ziti#1193]
*Experienced*

When configuring a controller with multiple hostnames/IPs SANs resolution to reach the API is correct, but which public key that is used to sign enrollment JWTs doesn't always match the intended case.

*Expected*

Enrollment JWTs can be created using a "default" hostname/IP or a specific hostname/IP on a case-by-case basis. The hostname/ip for the controller inside the JWT should match the signer.

*Reproduction*
1) Standup a controller with a private CA ("primary CA")
2) Enroll the controller with a public CA or a different private CA and ensure the SNA IP/DNS in the public certificate are different than the initial server certificate ("secondary CA")
3) Configure the Edge APIs to use the certificates from the secondary CA via `alt_server_certs`.
4) Set the advertised URL for enrollment to the secondary CA-issued certificates
5) Do not configure the root identity with any certs other than the default primary CA-issued ones
6) Attempt to enroll a new router or identity

**Comment by dovholuknf** [comment]
the "address" configured in the controller config file ___must___ align to the sever_cert/key in the identity block, not the alt_server_certs specified. It would be best if the controller would inspect the resolved `server_cert` and ensure the cert contains a SANS entry for the `address` specified. if not the controller should panic and inform the operator to fix the `server_cert` and that it must have a corresponding SANS for the address entered.

**Comment by qrkourier** [comment]
One solution is for the controller to enforce that the same private key is used whenever there are multiple server certs presented for the client API, selected by SNI. This works because the server's private key signs the OTT, and the server cert only serves to present the public key to the enrollee which then verifies the JWT's signature. If all server certs are presenting the same public key then JWT signatures will always be verifiable irrespective of which server cert is encountered.

**Comment by qmugnier** [comment]
Quick question, was this fixed? Because I think I encounter the same issue.

**Comment by andrewpmartinez** [comment]
This issue is also present in HA networks but proliferates to routers.

See HA Issue: https://github.com/openziti/ziti/issues/1980
