### ISSUE TITLE
Idea / feature request: Cloudflare as reverse proxy for Ziti Console, Controller and Routers

### ISSUE THREAD

**Issue by qdrddr** [openziti/ziti#1257]
Suppose Ziti is intended to be publically available on the internet. In that case, some services must be exposed to the public internet and add DNS public records. Therefore, sensitive and vital Ztiti components are discoverable to everyone and are open for DDoS and hacks.

To limit this malicious activity, please consider tuning Ziti Console, Controller, and Routers themselves to be hidden behind an **asynchronous** reverse proxy such as Cloudflare. Cloudflare provides a DNS server and a reverse proxy functionality alongside proper security functionality such as DDoS protection and IP Whitelisting using Cloudflare's Zone-level Web Application Firewall (WAF) and Configured IP Custom Lists.

These pieces of Cloudflare's functionality: CA Signed Certificate, DDoS protection & WAF IP Whitelisting, are free for everyone and can be highly efficient in protecting Ziti Console, Controller, and Routers from malicious activity.

PS. Ziti Console works behind Cloudflare reverse proxy perfectly well and is listed here as an example to illustrate the need better. Therefore only Controller and Routers must be fine-tuned to work over HTTPS behind an asynchronous proxy such as Cloudflare.

**Comment by philipleonardgriffiths** [comment]
Hey qdrddr, you have some misunderstandings on how Ziti works. Our fault, we obviously need to improve the documentation. Before giving a long write up, would you be open to a brief chat on your concerns as well as for me to explain how Ziti handles this issue you have raised (and the others)?

**Comment by smilindave26** [comment]
@philipleonardgriffiths what do you think @qdrddr misunderstood in this issue? Did you mean to post this on a different one?

**Comment by philipleonardgriffiths** [comment]
@smilindave26, a few things across the various posts incl.
1) outbound-only connections at source/destination of the dataplane (i.e., no listening port on overlay thus cannot be subject to DDoS, as well as solving CGNAT/overlapping IP issues, and no need for public DNS for the services) 
2) smart routing fabric for data plane so that the risk of DDoS is mitigated
3) controller's inherently need to be exposed to the network, that is the same for all overlay networks incl. Nebula, ZeroTier etc. we have implemented mTLS so that it does not respond to unauthenticated connections & developing HA in control plane mitigates risk
4) Ziti's focus on zero trust and deny-by-default which is why we do not allow endpoints to connect to controller unless they have a JWT, we do not want unknown endpoints trying to enrol

That said, we do have people in the community looking at UDP-hole punching and use of SPA methodology (single packet authenticate) but that these techniques also present an opportunity for enrollment token to be intercepted and used for malicious intent. 

Which is why I would love to have a deeper conversation to understand more about the intent and how the users issues could be resolved.

**Comment by qdrddr** [comment]
sure

**Comment by philipleonardgriffiths** [comment]
@qdrddr, cool. I don't know of a way to DM you on GH. Can you email me at philip.griffiths@netfoundry.io. We can agree a slot directly on mail.

**Comment by qdrddr** [comment]
@philipleonardgriffiths done

**Comment by philipleonardgriffiths** [comment]
Thanks. I will loop in @mikegorman-nf too.

**Comment by smilindave26** [comment]
Console can now be deployed protected by Ziti itself or zrok frontdoor
