### ISSUE TITLE
Missing Ziti released binaries for darwin on arm64

### ISSUE THREAD

**Issue by mjtrangoni** [openziti/ziti#1744]
Hi!

I just found out that the released assets are missing a tarball for Darwin on arm64. Only **ziti-darwin-amd64** is available.

Would it be possible to extend the CI for this?

Thank you!

**Comment by gberl002** [comment]
Hi @mjtrangoni, the Ziti binary for amd64 will work on arm64. We have another issue for this which is #652. At the time, GitHub actions didn't support a native darwin arm distribution. It looks like that might be fixed as of now. Since this is a duplicate, I will keep the original one in place, but we'll revisit it now that it looks like the roadblock has been removed.
