### ISSUE TITLE
What system do I need to run the router on

### ISSUE THREAD

**Issue by cltgit** [openziti/ziti#1773]
What system do I need to run the router on.
I want to test it in docker.
I used Ubuntu20.04 to generate a docker image and then started router tproxy in it.
The result was a failure.
It is guessed that systemctl may be the cause because it was found that the dns configuration could not be refreshed

**Comment by qrkourier** [comment]
@cltgit Yes, you can do that in Docker. You can use the official container image instead of building a custom image or using systemd. Would you like more specific instructions or Compose example? Here's an overview:

1. pull the openziti/ziti-router container image
3. create a Docker persistence (named) volume to store the router's state (identity, config, etc.)
2. generate a router configuration in the persistence volume and set filemode and owner to allow ziggy UID 2171 to write files 
3. run the container to enroll the router (generates identity materials in the mounted volume)
5. run the container with a restart policy so it stays running even after a reboot

**Comment by cltgit** [comment]
Thank you for your reply. I wanted to learn more about how the router intercepts requests. Initially, I started with the source code on my mac laptop, but I was told "failed to initialize tproxy interceptor: tproxy not supported on darwin". Then I tried to run it using docker, but the resolution failed "ziti-tunnel.resolver.test". I solved the problem by modifying the hosts file. In ziti, I defined the name of the service as "test.com". When I used nslookup to parse the test, I failed. I tried to parse the test in the router docker. My guess is docker mirroring, as my attempt to "systemd-resolved" was unsuccessful

**Comment by qrkourier** [comment]
Ah, you're using the router's `trproxy` mode, and the router is failing the DNS test at start-up because the container is not configured to send DNS questions to itself. I believe you can set the Docker container nameservers like `docker run --dns 127.0.0.1 --dns 1.1.1.1`.

**Comment by qrkourier** [comment]
As for testing tproxy interception in Docker, you must configure the router container and the second container that is initiating the network request to a Ziti service to share a container network namespace. 

```
docker run -d --name ziti-router-tproxy openziti/ziti-router
docker run -d --name client1 --network container:ziti-router-tproxy busybox
```

In this example, the BusyBox client container has access to any Ziti services that are authorized for the router's tunneler identity because they share a network namespace.

**Comment by qrkourier** [comment]
Here's a more detailed example that uses Docker Compose: https://github.com/openziti/ziti/blob/docker-router-example/dist/docker-images/ziti-router/README.md#tproxy-example
