### ISSUE TITLE
permissions enum doesn't contain "Invalid"

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1962]
When enumerating services as an administrator using the management api, such as `ziti edge list services -j`, if the identity doesn't have permissions because no service policy exists to grant the admin access, the permissions array returns "Invalid":
```
"permissions": [
                "Invalid"
            ]
```

This causes problems with generated clients because "Invalid" doesn't appear in the spec

**Comment by andrewpmartinez** [comment]
Tracing it through the code is because of the change to admin access where dial/bind is no longer assumed, and instead, `Invalid` is purposefully returned. 

The downside is that the spec was never updated, and any admin client accessing the service list will encounter similar errors. Most OpenAPI clients are generated with value checking for enumerations and will not accept unknown values. 

The workaround is to hand patch the `dialBind` enum and add `—Invalid` and then regenerate your client.

Once a new version of ziti is released with this issue fixed, upgrading and regenerating from the spec the controller provides will also fix the issue.
