### ISSUE TITLE
Support ACME v2

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#722]
Right now the ziti cli has "LE" support (let's encrypt) but it'd be even better if we could deliver a server cert from a verified CA like lets encrypt.

Implement the acme v2 spec https://letsencrypt.org/docs/client-options/ and allow the controllers to create/renew certificates for the external DNS/ip

**Comment by qrkourier** [comment]
A certificate management system provides verifiable certificate issuance and auto-renewal. Ziti shouldn't implement ACMEv2 because it's redundant and unnecessary. This is a job for the cloud provider itself. For example, if the application runs in AWS there's ACM which answers these needs, and in Kubernetes, there's Cert Manager which provides the same facilities for automated issuance and renewal. 

Scenario: Let's say we're running Traefik or Nginx as a Kubernetes Ingress Controller and wish to terminate TLS with a verifiable server certificate from Let's Encrypt. In this case, Cert Manager must be configured with an HTTP01 or DNS01 "solver." If your ingress is public then you have the option to use either. If private or if the requested certificate has a wildcard SAN then you must use the DNS01 solver, and there's no need for the ingress to be public, only that the DNS SAN is a global domain name for which the solver has an API integration.

If Ziti implements ACMEv2 then it will duplicate the function of the cloud provider by implementing the DNS API of many cloud providers in order to provide a DNS01 "solver" that allows Ziti to manage certificates.

In that light, it makes more sense for Ziti to terminate TLS with a bring-your-own certificate rather than to manage the full life cycle of the certificate and key material.

**Comment by dovholuknf** [comment]
I disagree.

**Comment by TetrusP** [comment]
I disagree as well

**Comment by smilindave26** [comment]
deferred. likey to revisit in future (@qrkourier to link related issue)

**Comment by qrkourier** [comment]
a more specific case in https://github.com/openziti/ziti/issues/2426

**Comment by j007bond007** [comment]
I also disagree... this is a huge missing piece whenever I and others think of OpenZiti replacing VPNs, Reverse Proxies, etc. Having SSL management built in would be amazing - no more need for complicated (and less secure) middleware with reverse proxies just to terminate SSL.

**Comment by qrkourier** [comment]
Since the genesis of this category of ideas, I'm put some mileage on a few solutions. One is using certificate managing proxies like Caddy and Nginx PM in-line with Ziti. With DNS solvers, these do provide trusted certs for web apps/svcs, but there are some drawbacks, too:

1. it's a complicated setup
2. the complexity creates an incentive to re-use the proxy for multiple services, which implies some trust that clients of one won't forge servername/host header to breach into the other

I'm hopeful this fork of Caddy could be more elegant and simplify and secure things by eliminating the hosting/server-side tunneler while providing cert management: https://github.com/openziti-test-kitchen/ziti-caddy

It's the closest thing I've found so far.
