### ISSUE TITLE
ZITI_PWD Plain Text Password

### ISSUE THREAD

**Issue by progmanos** [openziti/ziti#926]
Am I missing something? Why is the ZITI_PWD stored in plain text?

**Comment by dovholuknf** [comment]
You're not missing anything. The expressInstall is meant to get you going quickly and easily and it's intended to be used as a learning guide, not a hardened installation guide. I think it's a good idea though to add a step to the process/doc that points this fact out and to remove the line from the env file whenever you're ready.

**Comment by progmanos** [comment]
Why use that in the express install at all? How are you storing the passwords in a hardened install? It's fairly trivial to have a simple database to encrypt and salt passwords

**Comment by dovholuknf** [comment]
As to 'why', it's just due to convenience. The expresInstall function is just a small set of wrapper scripts that use the ziti CLI to setup an entire environment. It started years ago as a simple way for me to tear down, then stand up a new environment. Before you can use that CLI you need to authenticate to the controller. Storing the password in the .env file was just a convenient way for me to not have to bother with supplying the username nor password to login after the express install was complete. I could just source the .env file, doing so adds an alias to your shell called `zitiLogin`, then I could issue `zitiLogin` and the CLI was authenticated and now I could move on doing my ziti business. For the environments I tend to setup, and for devs/operators trying OpenZiti out, keeping that password in that file hasn't been a major concern yet. However, this exchange has me wondering how to balance that ease of loggin in with the practical reality that keeping a password (and username) in plain text is "not a great idea".

As for how to store passwords in a hardened environment the simple answer is "we don't". If one is looking to deploy an OpenZiti controller on the internet for long-term use, I'd certainly recommend against storing both the username and password in that file.  When you're at this level of maturity with OpenZiti, you've no doubt already discovered this (as you have) and either accept that risk or decide to remove the function/.env file etc.

**Comment by ekoby** [comment]
answered
