### ISSUE TITLE
Incorrect default ports on docker .env file

### ISSUE THREAD

**Issue by gooseleggs** [openziti/ziti#986]
The docker .env file, located here: https://github.com/openziti/ziti/blob/release-next/quickstart/docker/.env

is not defining default ports for the services.  Therefore, when the user does not define the variable (ie hashes it out for example), then the port reverts to the defined default which is not what is in the .env file.  

Reference: https://openziti.discourse.group/t/problems-with-docker-compose-setup-and-minecraft-example/1018

The docker-compose.yml file defines the ports to be used if the environment variables are not defined.  The .env file should mimic this by default.

Case in point `ZITI_EDGE_ROUTER_PORT` should be defined as 3022, and not 8442.

**Comment by arunbingari** [comment]
I would like to work on this ! Please assign me !

**Comment by dovholuknf** [comment]
@gberl002 - you have some changes in flight that might address this, right? @arunbingari -- if @gberl002 doesn't already have this accounted for, we'll let you know. thanks for volunteering!

**Comment by gberl002** [comment]
@arunbingari This one is also being fixed by my quickstart cleanup branch. I haven't tied it to the branch yet, sorry about that. 

I generally make a run through the issues after a PR is up, as some bugs get inadvertently fixed during other changes/fixes. I ran through the issues list just now, and I've updated any issues being fixed by my cleanup to be assigned to me and tied to my branch. So, if you want to look through the issues for another bug, anything not already assigned should be free to work on.
